version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  reviewers:
  - amatotsuji
  - aya-vii
  - lakesizebyter
  - arizuk
  - tadak1
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.0
    - 5.36.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.24.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
